//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIDINH
    {
        public string T_MA { get; set; }
        public string PDT_STT { get; set; }
        public string PDK_STT { get; set; }
        public int CD_SOLUONG { get; set; }
        public string CD_LIEUDUNG { get; set; }
        public string CD_CACHDUNG { get; set; }
    
        public virtual PHIEUDIEUTRI PHIEUDIEUTRI { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
