//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENMON()
        {
            this.CHUYENMONNHANVIEN = new HashSet<CHUYENMONNHANVIEN>();
        }
    
        public int CM_MA { get; set; }
        public string CM_TEN { get; set; }
        public string CM_MOTA { get; set; }
        public int VT_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENMONNHANVIEN> CHUYENMONNHANVIEN { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
