//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DG_LT
    {
        public string GDV_MA { get; set; }
        public int LT_MA { get; set; }
        public System.DateTime THOIGIAN { get; set; }
        public string DONGIA { get; set; }
    
        public virtual LIEUTRINH LIEUTRINH { get; set; }
        public virtual NGAY NGAY { get; set; }
    }
}
