//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAMGIA()
        {
            this.GIAMGOIDICHVU = new HashSet<GIAMGOIDICHVU>();
            this.GIAMGIA_PDK = new HashSet<GIAMGIA_PDK>();
            this.LGG_GG = new HashSet<LGG_GG>();
        }
    
        public string GG_MA { get; set; }
        public string GG_TEN { get; set; }
        public System.DateTime GG_NGAYBATDAU { get; set; }
        public System.DateTime GG_NGAYKETTHUC { get; set; }
        public string GG_NOIDUNG { get; set; }
        public string GG_TRANGTHAI { get; set; }
        public int GG_PHANTRAMGIAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGOIDICHVU> GIAMGOIDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGIA_PDK> GIAMGIA_PDK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGG_GG> LGG_GG { get; set; }
    }
}
