//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA_PDK
    {
        public string GG_MA { get; set; }
        public string PDK_STT { get; set; }
        public Nullable<int> ErrorHandling { get; set; }
    
        public virtual GIAMGIA GIAMGIA { get; set; }
        public virtual PHIEUDANGKY PHIEUDANGKY { get; set; }
    }
}
