//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOIDICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOIDICHVU()
        {
            this.DG_GDV = new HashSet<DG_GDV>();
            this.GIAMGOIDICHVU = new HashSet<GIAMGOIDICHVU>();
            this.LICHHEN = new HashSet<LICHHEN>();
            this.LIEUTRINH = new HashSet<LIEUTRINH>();
            this.PHIEUDANGKY = new HashSet<PHIEUDANGKY>();
            this.PHUTRACHGOI = new HashSet<PHUTRACHGOI>();
            this.DICHVUPHONG = new HashSet<DICHVUPHONG>();
        }
    
        public string GDV_MA { get; set; }
        public string GDV_TEN { get; set; }
        public Nullable<int> GDV_SOLAN { get; set; }
        public string GDV_MOTA { get; set; }
        public string GDV_ANH { get; set; }
        public int LGDV_MA { get; set; }
        public string DV_MA { get; set; }
        public string PP_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DG_GDV> DG_GDV { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual LOAIGOIDICHVU LOAIGOIDICHVU { get; set; }
        public virtual PHUONGPHAP PHUONGPHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGOIDICHVU> GIAMGOIDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHEN> LICHHEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIEUTRINH> LIEUTRINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDANGKY> PHIEUDANGKY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUTRACHGOI> PHUTRACHGOI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICHVUPHONG> DICHVUPHONG { get; set; }
    }
}
