//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.LICHHEN = new HashSet<LICHHEN>();
            this.PHIEUDANGKY = new HashSet<PHIEUDANGKY>();
        }
    
        public string KH_MA { get; set; }
        public string KH_HOTEN { get; set; }
        public System.DateTime KH_NGAYSINH { get; set; }
        public string KH_GIOITINH { get; set; }
        public string KH_DIACHI { get; set; }
        public string KH_SDT { get; set; }
        public string KH_EMAIL { get; set; }
        public Nullable<bool> KH_TRANGTHAIDANGNHAP { get; set; }
        public Nullable<int> XP_MA { get; set; }
    
        public virtual XAPHUONG XAPHUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHEN> LICHHEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDANGKY> PHIEUDANGKY { get; set; }
    }
}
