//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTRINHDIEUTRI
    {
        public string PDK_STT { get; set; }
        public string GDV_MA { get; set; }
        public int LT_MA { get; set; }
        public System.DateTime LTDT_NGAYDT { get; set; }
        public string LTDT_THOIGIANDEN { get; set; }
    
        public virtual PHIEUDANGKY PHIEUDANGKY { get; set; }
        public virtual LIEUTRINH LIEUTRINH { get; set; }
    }
}
