//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAMVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHLAMVIEC()
        {
            this.LICHHEN = new HashSet<LICHHEN>();
        }
    
        public string NV_MA { get; set; }
        public string CLV_MA { get; set; }
        public System.DateTime THOIGIAN { get; set; }
        public Nullable<int> P_MA { get; set; }
        public string LLV_GHICHU { get; set; }
    
        public virtual CALAMVIEC CALAMVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHEN> LICHHEN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NGAY NGAY { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
