//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHEN
    {
        public int LH_ID { get; set; }
        public System.DateTime LH_NGAYDEN { get; set; }
        public System.TimeSpan LH_THOIGIANDEN { get; set; }
        public string LH_GHICHU { get; set; }
        public string LH_TRANGTHAI { get; set; }
        public string KH_MA { get; set; }
        public string GDV_MA { get; set; }
        public string NV_MA { get; set; }
        public string CLV_MA { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    
        public virtual GOIDICHVU GOIDICHVU { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LICHLAMVIEC LICHLAMVIEC { get; set; }
    }
}
