//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIEUTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIEUTRINH()
        {
            this.DG_LT = new HashSet<DG_LT>();
            this.LICHTRINHDIEUTRI = new HashSet<LICHTRINHDIEUTRI>();
        }
    
        public int LT_MA { get; set; }
        public string GDV_MA { get; set; }
        public int LT_STT { get; set; }
        public string LT_MOTA { get; set; }
        public string LT_THOIGIANTH { get; set; }
        public Nullable<int> LT_NGAYTHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DG_LT> DG_LT { get; set; }
        public virtual GOIDICHVU GOIDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINHDIEUTRI> LICHTRINHDIEUTRI { get; set; }
    }
}
