//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CHUYENMONNHANVIEN = new HashSet<CHUYENMONNHANVIEN>();
            this.LICHLAMVIEC = new HashSet<LICHLAMVIEC>();
            this.NV_PDT = new HashSet<NV_PDT>();
            this.PHIEUDANGKY = new HashSet<PHIEUDANGKY>();
            this.PHIEUTHU = new HashSet<PHIEUTHU>();
            this.PHUTRACHGOI = new HashSet<PHUTRACHGOI>();
        }
    
        public string NV_MA { get; set; }
        public string NV_HOTEN { get; set; }
        public System.DateTime NV_NGAYSINH { get; set; }
        public string NV_GIOITINH { get; set; }
        public string NV_SDT { get; set; }
        public string NV_EMAIL { get; set; }
        public string NV_CCCD { get; set; }
        public string NV_DIACHI { get; set; }
        public string NV_USERNAME { get; set; }
        public string NV_PASSWORD { get; set; }
        public string NV_TRANGTHAI { get; set; }
        public string NV_ANH { get; set; }
        public Nullable<int> XP_MA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENMONNHANVIEN> CHUYENMONNHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_PDT> NV_PDT { get; set; }
        public virtual XAPHUONG XAPHUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDANGKY> PHIEUDANGKY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUTRACHGOI> PHUTRACHGOI { get; set; }
    }
}
