//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDANGKY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDANGKY()
        {
            this.GIAMGIA_PDK = new HashSet<GIAMGIA_PDK>();
            this.LICHTRINHDIEUTRI = new HashSet<LICHTRINHDIEUTRI>();
            this.PHIEUDIEUTRI = new HashSet<PHIEUDIEUTRI>();
        }
    
        public string PDK_STT { get; set; }
        public System.DateTime PDK_NGAYDK { get; set; }
        public System.DateTime PDK_NGAYBATDAU { get; set; }
        public string PDK_TRANGTHAI { get; set; }
        public string NV_MA { get; set; }
        public string GDV_MA { get; set; }
        public string KH_MA { get; set; }
        public int CTT_MA { get; set; }
    
        public virtual CACHTHANHTOAN CACHTHANHTOAN { get; set; }
        public virtual GOIDICHVU GOIDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGIA_PDK> GIAMGIA_PDK { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHTRINHDIEUTRI> LICHTRINHDIEUTRI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDIEUTRI> PHIEUDIEUTRI { get; set; }
    }
}
