//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDIEUTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDIEUTRI()
        {
            this.CHIDINH = new HashSet<CHIDINH>();
            this.NV_PDT = new HashSet<NV_PDT>();
            this.PT_PDT = new HashSet<PT_PDT>();
        }
    
        public string PDT_STT { get; set; }
        public string PDK_STT { get; set; }
        public System.DateTime PDT_NGAYLAP { get; set; }
        public string PDT_CHUANDOAN { get; set; }
        public string PDT_GHICHU { get; set; }
        public string PDT_LOIDAN { get; set; }
        public string PDT_TRANGTHAI { get; set; }
        public bool PDT_TRANGTHAINNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIDINH> CHIDINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_PDT> NV_PDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PT_PDT> PT_PDT { get; set; }
        public virtual PHIEUDANGKY PHIEUDANGKY { get; set; }
    }
}
