//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVTN_QLSpa.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTRACHGOI
    {
        public string GDV_MA { get; set; }
        public string NV_MA { get; set; }
        public System.DateTime PTG_NGAY { get; set; }
        public string PTG_TRANGTHAI { get; set; }
    
        public virtual GOIDICHVU GOIDICHVU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
